name          '3dna-pgbouncer'
version       '0.1.0'
source        'https://github.com/3dna/3dna-pgbouncer/'
author        '3dna'
license       'BSD-3'
summary       'sets up and configures pgbouncer'
description   'sets up and configures pgbouncer'
project_page  'https://github.com/3dna/3dna-pgbouncer/'

dependency 'puppetlabs/stdlib'
